name = "LoveItAgain"
license = "GPL V3"
licenselink = "https://github.com/thomas-louvigne/LoveItAgain/blob/main/LICENSE"
description = "A Clean, Elegant but Advanced Hugo Theme for Hugo. (Fork of LoveIt)"

homepage = "https://thomas-louvigne.github.io/"
demosite = "https://thomas-louvigne.github.io/"

tags = [
  "blog",
  "clean",
  "responsive",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]

min_version = "0.62.0"

[author]
  name = "Thomas Louvgine"
  homepage = "https://thomas-louvigne.github.io/"

[original]
  name = "Fastbyte01"
  homepage = "https://www.fsb01.com/"
  repo = "https://github.com/Fastbyte01/KeepIt"
