baseURL = "https://sschueller.github.io"
title = "Stefan Schüller"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

theme = "DoIt"

[params]
  canonicalURL = "https://stefan.schueller.net"
